
# Properties file for local/dev enviroment
# You need to configure the environment variable in your IDE, more info in README.md
# Overrides application.yml default properties

spring:
  datasource:
    #initialization-mode: always
    #data: classpath:/data.sql
    # Use host and db when connecting to Fury db, host is the same, db is the name of your schema
    ##host: proxysql.master.meliseginf.com:6612
      ##db: testfinal
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/automotriz_delux?useSSL=true&serverTimezone=UTC&characterEncoding=UTF-8
    ##username: ${LOCAL_DB_USER}
    ##password: ${LOCAL_DB_PASS}
    ##initialization-mode: always
    username: root
    password: root1234

  jpa:
    open-in-view: true
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    ##database-platform: org.hibernate.dialect.MySQL8Dialect
      database-platform: org.hibernate.dialect.MySQL57Dialect

